### PR TITLE
Fix promises

### PR DESCRIPTION
**Pull request by selfagency**
Supersedes #119. Signed-off-by: Daniel Sieradski <daniel@self.agency>

### CODE REVIEW

**Comment by benbrown** [comment]
OK sooooo, what if I explicitly do NOT want to await all of those promises, because i want them to just all spool off in the background while the rest of the process continues?

**Comment by selfagency** [comment]
@benbrown you need an independent [promise queue](https://www.npmjs.com/package/queue-promise)

**Comment by benbrown** [comment]
@selfagency that does seem like the responsible thing to do.

**Comment by benbrown** [comment]
oh that library looks delightful.

**Comment by benbrown** [comment]
I intend to refactor to using the promise queue when i merge this. Soon!

**Comment by benbrown** [comment]
This has been fixed and I added the promise queue. Handy!!

**Pull request closed without merging**
