### PR TITLE
EXPERIMENTAL: Feed/inbox view

### LINKED ISSUE #18: Feature: Ability to view posts in an inbox-style view
Similar to the DM view - see a list of all people I am following, and let me navigate them as an inbox of posts similar to a feed reader.

### PR DESCRIPTION
**Pull request by benbrown**
This adds a `/private/feeds` url to the service.

This imagines all the people you are following as "Feeds"

This provides an interface for viewing 1 "feed" at a time.
It sorts the list of feeds by most recent update.

- [x] Unread ~counts~ indicator for each feed
- [x] Is this the same as the following page maybe or maybe just part of global nav
- [x] And maybe even the same as individual profiles?

anyways this is far from finished

will resolve #18

### CODE REVIEW

**Comment by benbrown** [comment]
Super rough
Screen Shot 2023-01-06 at 11 06 45 PM

**Comment by PurpleStarChild** [comment]
Loving this new feed display! I hope it makes its way into the main branch eventually. Also love the idea of having an unread count.

**Comment by benbrown** [comment]
Thanks @PurpleStarChild  I am definitely planning on including it, but first I have to decide on how to integrate it. I am leading torwards a Feedly-style thing, were at the top of the nav we'd still have the Feed, notifications, inbox, but then right into a list of recently updated people.

**Comment by benbrown** [comment]
This is looking pretty good! 

Below the main nav, there are the 20 most recently updated people. Clicking them goes to their feed that right now includes posts and replies - some that you may not normally see in the "latest" feed.

Screen Shot 2023-01-11 at 10 06 52 PM

**Pull request merged**
